### ISSUE TITLE
Ingress change blocks incoming traffic

### ISSUE THREAD

**Issue by claaslisowski** [cloudposse/terraform-aws-elasticsearch#10]
The change from `-1` to `tcp` without setting specific to and from ports blocks all incoming traffic.

[I've commented it here, as well](https://github.com/cloudposse/terraform-aws-elasticsearch/commit/4eb9a7d6627fdf5e07c2fdef6026ae73af3b1aae)

Port 443 ~and 80~ should be allowed incoming.

**Comment by aknysh** [comment]
@claaslisowski 
thanks
we need to revert it back to `-1`.
I think it was some other issue

**Comment by claaslisowski** [comment]
Thanks a lot @goruha. That fix works fine.
