### ISSUE TITLE
No support for autotune

### ISSUE THREAD

**Issue by McTristan** [cloudposse/terraform-aws-elasticsearch#121]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
It seems the auto_tune settings are not supported. The following set of configuration parameters won't work:

```
auto_tune_options {
    desired_state       = "ENABLED"
    rollback_on_disable = "NO_ROLLBACK"
    maintenance_schedule {
      cron_expression_for_recurrence = "cron(0 0 ? * 1 *)"
      start_at                       = "2021-07-21T03:02:23Z"
      duration {
        unit  = "HOURS"
        value = 2
      }
    }
  }
```

From the description it seems to be missing, however we do believe it should be there.
Everytime we call terraform apply the above mentioned change (from outside the terraform stack) is shown.

## Expected Behavior

I expect to have the auto_tune_options as parameters so I don't always see that I've made changes outside of my terraform stack.

## Steps to Reproduce
1. Try to use the above mentioned codeblock with the cloudposse elasticsearch module
2. Run 'terraform apply'
3. See error ' Error: Unsupported block type '

## Additional Context

It seems this module is kind of outdated as also using the new OpenSearch-version as "ElasticSearch"-version is not working correctly. It will destroy the cluster everytime we call "terraform apply".

**Comment by McTristan** [comment]
To use OpenSearch you have to set "OpenSearch_x.x" (while x.x is the version you want to use i.e. 1.1), took me a while to figure that one out.

**Comment by Mcrivar** [comment]
> 

@McTristan where that is set in the module?

**Comment by McTristan** [comment]
@Mcrivar 
Regarding the opensearch version, just use the elasticsearch_version field and enter "OpenSearch_x.x" - it is a bit confusing but it just starts there. They also renamed the instance types in the UI but it seems they have a mapping. So m5.large.elasticsearch becomes m5.large.search and so on.

I'm not sure which part of my posting you mean by 'where that is set in the module?'. Is it regarding the not implemented yet autotune parameter?

**Comment by Mcrivar** [comment]
> @Mcrivar Regarding the opensearch version, just use the elasticsearch_version field and enter "OpenSearch_x.x" - it is a bit confusing but it just starts there. They also renamed the instance types in the UI but it seems they have a mapping. So m5.large.elasticsearch becomes m5.large.search and so on.
> 
> I'm not sure which part of my posting you mean by 'where that is set in the module?'. Is it regarding the not implemented yet autotune parameter?

Thanks!

I meant the OpenSearch version.

**Comment by iCodeOkay** [comment]
Stumbled across the lack of support for autotune today as well!

**Comment by MatiasNielsen** [comment]
There's still no way to enable auto tune on this & Maintenance window?
