### ISSUE TITLE
kibana_hostname contains invalid records

### ISSUE THREAD

**Issue by thoellrich** [cloudposse/terraform-aws-elasticsearch#14]
When `dns_zone_id` is supplied, the module attempts to create a CNAME Route53 record for the domain's Kibana endpoints. These endpoints look like "`xxx.<region>.es.amazonaws.com/_plugin/kibana`". Using these records as the entries for a CNAME results in errors when one tries to resolve the newly create Route53 entry. The path "`/_plugin/kibana`" must not be part of the records.

Possible solutions: 
- remove creation of the kibana related DNS entries alltogether
*or*
- use the same records for the `kibana_hostname` as used for the `domain_hostname`: `records   = ["${aws_elasticsearch_domain.default.*.domain_endpoint}"]`

**Comment by Chris-Softrams** [comment]
When will there be a release with this fix?

**Comment by joe-niland** [comment]
It looks like the change made in #47 was reverted here https://github.com/cloudposse/terraform-aws-elasticsearch/commit/c7bc8c821fa95364c39ebf7504fadf3ba9dd8a5d#diff-7a370d8342e7203b805911c92454f0f4R265

@Chris-Softrams are you using release 0.20.4 and is it not working?

**Comment by Chris-Softrams** [comment]
Yep using 0.20.4 and the r53 record for kibana is still adding `/_plugin/kibana`
