### ISSUE TITLE
Invalid Domain Name

### ISSUE THREAD

**Issue by biskandar** [cloudposse/terraform-aws-elasticsearch#18]
# cat main.tf

provider "aws" {
  region = "ap-southeast-1"
  version = "~> 2.15"
}

provider "null" {
  version = "~> 2.1"
}

module "elasticsearch" {
  source                  = "git::https://github.com/cloudposse/terraform-aws-elasticsearch.git?ref=master"
  namespace               = "eg"
  stage                   = "dev"
  name                    = "es"
  dns_zone_id             = "Z25Y69PJJVXXXX"
  security_groups         = ["sg-0bebedf9d19xxxxxx"]
  vpc_id                  = "vpc-0f9576da430xxxxxx"
  subnet_ids              = ["subnet-0c3a9905724xxxxxx"]
  zone_awareness_enabled  = "true"
  elasticsearch_version   = "5.6.16"
  instance_type           = "m4.large.elasticsearch"
  instance_count          = 4
  iam_role_arns           = ["arn:aws:iam::12364176xxxx:role/es"]
  iam_actions             = ["es:ESHttpGet", "es:ESHttpPut", "es:ESHttpPost"]
  encrypt_at_rest_enabled = "true"
  kibana_subdomain_name   = "kibana-es"

  advanced_options {
    "rest.action.multi.allow_explicit_index" = "true"
  }
}

# terraform init
Initializing modules...
- module.elasticsearch
- module.elasticsearch.label
- module.elasticsearch.user_label
- module.elasticsearch.domain_hostname
- module.elasticsearch.kibana_hostname

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

# terraform apply

Error: module.elasticsearch.aws_elasticsearch_domain.default: "domain_name" must start with a lowercase alphabet and be at least 3 and no more than 28 characters long. Valid characters are a-z (lowercase letters), 0-9, and - (hyphen).

**Comment by goruha** [comment]
We just add new variable allow developers to config domain name

https://github.com/cloudposse/terraform-aws-elasticsearch/blob/0.13.0/variables.tf#L227

**Comment by vikram-yerneni** [comment]
This issue still persists. Even with defining a variable "elasticsearch_subdomain_name" (variable name: test-domain-001), terraform plan is still failing with picking up 
`Error: invalid value for domain_name (must start with a lowercase alphabet and be at least 3 and no more than 28 characters long. Valid characters are a-z (lowercase letters), 0-9, and - (hyphen).)
with module.elasticsearch.aws_elasticsearch_domain.default[0],
on .terraform/modules/elasticsearch/main.tf line 102, in resource "aws_elasticsearch_domain" "default":
102:   domain_name           = module.this.id`


Somehow its not picking up the variable defined.

**Comment by Gowiem** [comment]
@vikram-yerneni @nnt this issue is due to some confusing terminology I believe... The [`domain_name` value is set as `module.this.id`](https://github.com/cloudposse/terraform-aws-elasticsearch/blob/a216b2797b190ac0b996918c4c93cf16bf2e0425/main.tf#L102) which needs to satisfy the constraints that have been mentioned. `module.this.id` is from https://github.com/cloudposse/terraform-null-label and the collection of `namespace`, `stage`, `environment`, `name` and similar parts. You'll need to adjust those to correctly get the `domain_name` value to be valid. 

Please try that out and post back with your actual code if you're still experiencing issues.

I'm going to close this issue as I believe it's just a miscommunication which I've hopefully just rectified. Thanks folks!

**Comment by vikram-yerneni** [comment]
@Gowiem Instead of all four variables namespace, stage, environment, name (based on my colleagues advice), I went with name variable and it worked. 
Thanks for the inputs here. Appreciate it.
