### ISSUE TITLE
make creation of elasticsearch user not mandatory

### ISSUE THREAD

**Issue by rverma-nikiai** [cloudposse/terraform-aws-elasticsearch#22]
The default behavior is to create an iam user to access elasticsearch. We manage the creation of users separately and would like to continue that. The module should allow passing the user list(and even empty list) to grant credentials and avoid creating the default user.

**Comment by Gowiem** [comment]
@rverma-nikiai the role (user) resource is only enabled when the `var.iam_authorizing_role_arns` and `var.iam_role_arns` are non-empty. This seems to satisfy this request. See the code for full insight: https://github.com/cloudposse/terraform-aws-elasticsearch/blob/a216b2797b190ac0b996918c4c93cf16bf2e0425/main.tf#L69

Please reopen if that is not the case!
