### ISSUE TITLE
Fix `zone_awareness_config` config part

### ISSUE THREAD

**Issue by netflash** [cloudposse/terraform-aws-elasticsearch#24]
Hi there,

I have an issue with `zone_awareness_config`,

this parameter's nested `availability_zone_count` can either be set to `2` or `3` or omitted at all. I can't set it to one.
So if I set `zone_awareness_enabled = false` and `availability_zone_count = 2`

Every time I run terraform plan I get this

```
      ~ cluster_config {
            dedicated_master_count   = 0
            dedicated_master_enabled = false
            instance_count           = 1
            instance_type            = "t2.small.elasticsearch"
            zone_awareness_enabled   = false

          + zone_awareness_config {
              + availability_zone_count = 2
            }
        }
```

Expected behaviour - If `availability_zone_count` is set to `1`, omit this config part at all.

I'm looking into what I can done to fix it and probably will send a pull-request later on.

**Comment by look4regev** [comment]
Guys, any progress please with merging the PR^? This issue is really annoying. Thanks.

**Comment by ivanmartos** [comment]
Issue occurs again in version `0.33.3`
