### ISSUE TITLE
Add support of `cognito authentication` config block

### ISSUE THREAD

**Issue by netflash** [cloudposse/terraform-aws-elasticsearch#26]
The module currently does not support `cognito_options` config block.
See [https://www.terraform.io/docs/providers/aws/r/elasticsearch_domain.html](https://www.terraform.io/docs/providers/aws/r/elasticsearch_domain.html) for details.

It would be good to have this feature supported.

**Comment by jamesopti** [comment]
Is there a workaround for this at the moment? Can I import the domain configured by this module using `resource "aws_elasticsearch_domain" "module_created_es_domain" {` ?

**Comment by karthikeayan** [comment]
Terraform AWS Provider having a limitation to enable fine grained access control.

https://github.com/terraform-providers/terraform-provider-aws/issues/12054

**Comment by 3h4x** [comment]
@netflash @jamengual 

Cognito is supported:
https://github.com/cloudposse/terraform-aws-elasticsearch/blob/e7c77c97f56cb3f2b060fe3401faab947b4d78a6/main.tf#L179-L184
