### ISSUE TITLE
Reserved instances

### ISSUE THREAD

**Issue by Glen-Moonpig** [cloudposse/terraform-aws-elasticsearch#36]
Is there any support for creating reserved instances?

**Comment by Gowiem** [comment]
@Glen-Moonpig Can you provide some more information here? AFAIU, you would first reserve instances via AWS Billing and then create the ES instances via this module. Or is there some reserved instance resource we're not utilizing in this module? 

Please close out if this is no longer relevant -- Thanks!

**Comment by Glen-Moonpig** [comment]
> @Glen-Moonpig Can you provide some more information here? AFAIU, you would first reserve instances via AWS Billing and then create the ES instances via this module. Or is there some reserved instance resource we're not utilizing in this module?
> 
> Please close out if this is no longer relevant -- Thanks!

Yes I think manually creating the reserved instances would be the solution. I had hoped it could be managed by terraform somehow to avoid manual deployment work, but there is no terraform resources for this.

**Comment by kevcube** [comment]
sorry, thought this was RDS.
