### ISSUE TITLE
Error creating ElasticSearch domain: ValidationException:

### ISSUE THREAD

**Issue by bhanu1503-bhadauria** [cloudposse/terraform-aws-elasticsearch#40]
Error: Error creating ElasticSearch domain: ValidationException: 

  on terraform-aws-elasticsearch/main.tf line 104, in resource "aws_elasticsearch_domain" "default":
 104: resource "aws_elasticsearch_domain" "default" {

**Comment by yariksheptykin** [comment]
I ran into a similar issue using the example provided in README. The error message also mentioned:
```
Error: invalid value for domain_name (must start with a lowercase alphabet and be at least 3 and no more than 28 characters long. Valid characters are a-z (lowercase letters), 0-9, and - (hyphen).)
```
Examples in README use "es" value for name which is being used for DNS Name. This appears to be too short. After using `name= "elasticsearch"` the error message disappeared.

**Comment by aknysh** [comment]
please try the latest master.
will close for now, we can reopen if any issues
