### ISSUE TITLE
Module fails if ES service linked role doesn't exist

### ISSUE THREAD

**Issue by joe-niland** [cloudposse/terraform-aws-elasticsearch#44]
I found that this module wouldn't work unless I created the ES service linked role first (for service "es.amazonaws.com").

The reason for this is that if the role doesn't already exist the data source element fails (https://github.com/cloudposse/terraform-aws-elasticsearch/blob/master/main.tf#L68) and the module won't complete.

The `create_iam_service_linked_role` variable was added a while ago to deal with this issue, however it seems the variable value is not used.

## Expected Behavior

The module should run even if the service linked role doesn't exist

## Steps to Reproduce

1. Include this module, setting variable `create_iam_service_linked_role` to true
3. `terraform apply`

## Environment (please complete the following information):

TF 0.12.21

**Comment by igable** [comment]
If anyone is looking for a workaround until this issue is resolved all you need to do is:

`aws iam create-service-linked-role --aws-service-name es.amazonaws.com`
