### ISSUE TITLE
security_groups ignored

### ISSUE THREAD

**Issue by holisticode** [cloudposse/terraform-aws-elasticsearch#62]
## Describe the Bug
Whatever is in `security_groups` seems to be ignored

## Expected Behavior
Security groups specified in `security_groups` should be applied

## Steps to Reproduce
`security_groups = [aws_security_group.my_group1.id, aws_security_group.my_group2.id]`

## Screenshots
Output of `terraform plan`:

```
 ~ vpc_options {
            availability_zones = [
               <LIST>
            ]
          ~ security_group_ids = [
              - "sg-<my_group1.id>",
              - "sg-<my_group2.id>",
                "sg-<generated-group.id>",
              - "sg-<manually_added_group.id>",
            ]
```

In the above output, terraform is again trying to remove the groups I have *manually* added to the ES domain configuration via the AWS Web UI because in a previous run they did NOT get applied.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: ubuntu on AWS
 - Version 18.04

**Comment by mrsiejas** [comment]
Hi, can have a look at this issue - got tf experience. Terraform has perculiar way of interpreting lists. Tf is trying to remove anything which was not applied via tf itself and not stored in tf state file.

**Comment by etessari** [comment]
I'm experiencing the same issue, I created everything via terraform cli so It could not be a conflict with terraform state, I think its a bug.

**Comment by devops-nfq** [comment]
Yup me too. Try to add more security group but still not apply

**Comment by king131** [comment]
Same issue.

**Comment by king131** [comment]
I had found that, in the` .terraform/modules/elasticsearch/main.tf` line 164,the code `security_group_ids = [join("", aws_security_group.default.*.id)]` ,this security did not add any security_group content which we add in the parent module. 

So, i added my security group id  here manually. It's working. Like this `security_group_ids = [join("", aws_security_group.default.*.id),"sg-xxxxxxxx"]`

**Comment by lbrulet** [comment]
Same issue.

**Comment by lgiuliani-mwb** [comment]
The `security_groups` configuration option refers to the security groups that have access to the cluster' security group. This is an excerpt of a plan:

```  # module.elasticsearch.aws_security_group_rule.ingress_security_groups[3] will be created
  + resource "aws_security_group_rule" "ingress_security_groups" {
      + description              = "Allow inbound traffic from Security Groups"
      + from_port                = 0
      + id                       = (known after apply)
      + protocol                 = "tcp"
      + security_group_id        = (known after apply)
      + self                     = false
      + source_security_group_id = "sg-AAAAAAA"
      + to_port                  = 65535
      + type                     = "ingress"
    }
```

Each specified SG will create a new ingress rule.

**Comment by acmitch** [comment]
Any update on this? Can we escalate?
