### ISSUE TITLE
Support for Ultrawarm nodes

### ISSUE THREAD

**Issue by jchristner-trustwave** [cloudposse/terraform-aws-elasticsearch#69]
The terraform aws_elasticsearch_domain resource supports the Ultrawarm nodes via "warm_enabled", "warm_count", and "warm_type" options.   It would be great if this module could as well.

**Comment by maciejasembler** [comment]
I have opened a https://github.com/cloudposse/terraform-aws-elasticsearch/pull/71 since I need it kinda bad and do not want to maintain my own fork.

Note, I have not yet tested that entirely :) but you can review if it meets your coding standards.

~asm

**Comment by maciejasembler** [comment]
Well I have tested it on my side - works as expected.

**Comment by maciejasembler** [comment]
May I please ask for review here ?

https://github.com/cloudposse/terraform-aws-elasticsearch/pull/71

**Comment by maciejasembler** [comment]
Recreated MR as https://github.com/cloudposse/terraform-aws-elasticsearch/pull/74

I messed while rebasing -_-'

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/terraform-aws-elasticsearch/pull/74
