### ISSUE TITLE
Only one log type can be chosen

### ISSUE THREAD

**Issue by claaslisowski** [cloudposse/terraform-aws-elasticsearch#7]
Currently only one log type can be chosen.
```
log_publishing_options {
    enabled                  = "${var.log_publishing_enabled }"
    log_type                 = "${var.log_publishing_log_type}"
    cloudwatch_log_group_arn = "${var.log_publishing_cloudwatch_log_group_arn}"
}
```

It would be useful if more than one and optionally all 3 types can be enabled at once.

Maybe this way?
```
log_publishing_options {
    enabled                  = "${var.log_publishing_index_enabled }"
    log_type                 = "INDEX_SLOW_LOGS"
    cloudwatch_log_group_arn = "${var.log_publishing_index_cloudwatch_log_group_arn}"
}

log_publishing_options {
    enabled                  = "${var.log_publishing_search_enabled }"
    log_type                 = "SEARCH_SLOW_LOGS"
    cloudwatch_log_group_arn = "${var.log_publishing_search_cloudwatch_log_group_arn}"
}

log_publishing_options {
    enabled                  = "${var.log_publishing_application_enabled }"
    log_type                 = "ES_APPLICATION_LOGS"
    cloudwatch_log_group_arn = "${var.log_publishing_application_cloudwatch_log_group_arn}"
}
```

**Comment by aknysh** [comment]
@claaslisowski  thanks!!
it looks like a good addition.
we can take a look at it this week, or you can test and open a PR - we'll review it promptly

**Comment by claaslisowski** [comment]
@aknysh,
I can create a PR from my fork. 

Just the question of you want to have backwards compatibility?

Since there are no overlapping variables used the current log_publishing_options block could be appended at the end and would therefore overwrite the defaults _false_ with _true_ in case the old way is used.

Would look this way and works.
```

  log_publishing_options {
    enabled                  = "${var.log_publishing_index_enabled }"
    log_type                 = "INDEX_SLOW_LOGS"
    cloudwatch_log_group_arn = "${var.log_publishing_index_cloudwatch_log_group_arn}"
  }

  log_publishing_options {
    enabled                  = "${var.log_publishing_search_enabled }"
    log_type                 = "SEARCH_SLOW_LOGS"
    cloudwatch_log_group_arn = "${var.log_publishing_search_cloudwatch_log_group_arn}"
  }

  log_publishing_options {
    enabled                  = "${var.log_publishing_application_enabled }"
    log_type                 = "ES_APPLICATION_LOGS"
    cloudwatch_log_group_arn = "${var.log_publishing_application_cloudwatch_log_group_arn}"
  }

  log_publishing_options {
    enabled                  = "${var.log_publishing_enabled }"
    log_type                 = "${var.log_publishing_log_type}"
    cloudwatch_log_group_arn = "${var.log_publishing_cloudwatch_log_group_arn}"
 }

```

**Comment by aknysh** [comment]
@claaslisowski 
that should work.

also, we don't worry about backwards compatibility since we pin each module to a release everywhere we use it.

another way of doing it would be to provide a list of maps:

variable  log_publishing_options_list {
  type = "list"
  default = [
     {
      log_type                 = "INDEX_SLOW_LOGS"
      cloudwatch_log_group_arn = "......."
     },
    {
      log_type                 = "SEARCH_SLOW_LOGS"
      cloudwatch_log_group_arn = "......."
     },
     {
      log_type                 = "ES_APPLICATION_LOGS"
      cloudwatch_log_group_arn = "......."
     }
 ]
  description = "List of maps for log publishing options"
}

so the user of the module would provide a complete list of maps.

log_publishing_options = "${var.log_publishing_options_list}"

@osterman which way do you think is better?

**Comment by osterman** [comment]
@aknysh I think the approach by @claaslisowski might be better here if the `cloudwatch_log_group_arn` can be the same.  The boolean enabled flag also makes it easier. But the lack of idempotency is unfortunate.

@claaslisowski can you see if the method @aknysh proposes provides idempotency.

**Comment by claaslisowski** [comment]
@osterman ,
the solution from my first comment, **without the backwards compatibility,** was  idempotent for me. 

Only the solution including backwards compat. lacked the idempotency.

But I also noticed some days ago similar issue like this 
https://github.com/terraform-providers/terraform-provider-aws/issues/5752

**Comment by osterman** [comment]
@claaslisowski I'm okay with the first implementation then. Like @aknysh said, we're not concerned with backwards compatibility in pre-1.0 releases and we version pin everything for stability.

@aknysh thoughts? Okay to go with #1?
