### ISSUE TITLE
The dependency module terraform-aws-route53-cluster-hostname pulls a lower version of terraform which is a breaking change

### ISSUE THREAD

**Issue by keshav-niki** [cloudposse/terraform-aws-elasticsearch#70]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
The latest version of this module declares a dependency on an outdated version of terraform-aws-route53-cluster-hostname(0.3.0). This version declares 0.12 of terraform as a required depdendency while rest of modules and overall cluster config depends on 0.13. Can we increase the version of terraform-aws-route53-cluster-hostname to 0.5.0 in latest release of this module?

**Comment by Gowiem** [comment]
This has been fixed in a recent version. Closing out.
