### ISSUE TITLE
Allow defining a certificate

### ISSUE THREAD

**Issue by Spritekin** [cloudposse/terraform-aws-elasticsearch#79]
## Describe the Feature
Allow defining a certificate for the domain.

When I setup a name for the ES or Kibana services like this:

  domain_hostname_enabled = true
  elasticsearch_subdomain_name = "elasticsearch"
  kibana_hostname_enabled = true
  kibana_subdomain_name   = "kibana"
  dns_zone_id             = aws_route53_zone.hosted_zone.zone_id

The records are correctly setup in Route53 and I can see kibana.my.domain.com pointing to the correct URL (the long ugly one). However when I try to navigate to the service using this pretty name I get an error message in the browser because it uses the AWS ugly certificate. I can't find a way to set my own certificate.

## Expected Behavior

I would like to setup a certificate for my.domain.com from the ACM. Notice the AWS UI has an option exactly for that purpose.

## Use Case

Should allow setting up the certificate for my alternate name. 

## Describe Ideal Solution

Pass the certificate ARN as a variables and it will be registered in the domain.

## Alternatives Considered

Setting up an ELB... but the ES already has the functionality.

## Additional Context

Screenshot shows the ES certificate which won't work with my kibana.my.domain.com name

<img width="466" alt="Screen Shot 2020-11-11 at 8 02 05 pm" src="https://user-images.githubusercontent.com/13467740/98791238-dc7f8a00-2458-11eb-91cd-f0b0eb4783dc.png">

**Comment by christiangjengedal** [comment]
Requires https://github.com/hashicorp/terraform-provider-aws/issues/16059 ?

**Comment by Gowiem** [comment]
@Spritekin @christiangjengedal we now have https://github.com/cloudposse/terraform-aws-elasticsearch#input_custom_endpoint_certificate_arn which I believe would satisfy this constraint. I'm going to close out. Please reopen if I'm mistaken.
