### ISSUE TITLE
Allow disabling elasticsearch resource policy in the module

### ISSUE THREAD

**Issue by janlud** [cloudposse/terraform-aws-elasticsearch#83]
## Describe the Feature

I want to use my own elasticsearch domain policy as the module doesn't allow me to configure what I want - Conditions with AWS Organizations IDs.

## Expected Behavior

The policy should allow any possible scenario a user can have.

## Use Case

I need to allow IAM principals from my organization/OU to Elasticsearch. I don't know the roles when creating the Elasticsearch and I also don't know CIDRs of the VPCs beforehand. And I don't want to open the domain to anyone (even in VPC) when there is a AWS condition key to make this better.

```
"Condition": {
        "StringEquals": {
          "aws:PrincipalOrgID": "o-abcdefgh"
        }
      }
```

## Describe Ideal Solution

Module would take all the IAM resource policy inputs and create correct policy.

## Alternatives Considered

Creating the policy outside of the module but it shows diff between runs.

**Comment by abeluck** [comment]
We also have this issue, namely that we'd like to be able to configure the domain access policy ourselves. In our case we want an open access policy, because all nodes in the VPC subnet should be able to access the domain (and we've setup the appropriate SGs).

**Comment by bodgit** [comment]
Stumbled onto this issue as well, couldn't work out how to apply the open access policy to a new domain.

**Comment by bodgit** [comment]
If you don't specify the `iam_role_arns`  or `iam_authorizing_role_arns` attributes then no domain policy resource is created. You can then create the `aws_elasticsearch_domain_policy` resource directly yourself outside of the module. Something like this achieves the open access policy:
```hcl
module "this" {
  source = "cloudposse/elasticsearch/aws"
  ...
}

data "aws_iam_policy_document" "this" {
  statement {
    effect = "Allow"

    actions = [
      "es:*",
    ]

    resources = [
      "${module.this.domain_arn}/*",

    ]

    principals {
      type = "AWS"

      identifiers = [
        "*",
      ]
    }
  }
}

resource "aws_elasticsearch_domain_policy" "this" {
  domain_name     = module.this.domain_name
  access_policies = data.aws_iam_policy_document.this.json
}

```
