### ISSUE TITLE
New AUDIT_LOG enable feature break builds as it is not supported in all `>= 2.0` AWS Provider

### ISSUE THREAD

**Issue by sherifabdlnaby** [cloudposse/terraform-aws-elasticsearch#93]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Introduced by #86, the option to add AUDIT_LOGGING is not compatible with all `>= 2.0` AWS providers.
Which leads to :
```
Error: expected log_publishing_options.0.log_type to be one of [INDEX_SLOW_LOGS SEARCH_SLOW_LOGS ES_APPLICATION_LOGS], got AUDIT_LOGS

  on .terraform/modules/elasticsearch/main.tf line 100, in resource "aws_elasticsearch_domain" "default":
 100: resource "aws_elasticsearch_domain" "default" {
```

Enforcing a >=3 version in my wrapping module fixed it.

**Comment by sherifabdlnaby** [comment]
AWS Provide 3.8 is the most recent version that supports AUDIT_LOG

**Comment by Gowiem** [comment]
@sherifabdlnaby we not explicitly pin `>= 3.35.0` for the AWS provider in this module. I believe that satisfies this issue. 

See https://github.com/cloudposse/terraform-aws-elasticsearch/blob/a216b2797b190ac0b996918c4c93cf16bf2e0425/versions.tf#L7

Please reopen if I'm mistaken. Thanks!
